# Default values for threedb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch-oss
  tag: 6.2.3
  pullPolicy: IfNotPresent


ingress:
  enabled: False
